/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-12-22 07:44:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.wap;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_005fnew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<title>首页</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<link href=\"../../../css/init.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"\" rel=\"stylesheet\" id=\"device\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../../js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../../../js/jquery.qrcode.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap dpn\" id=\"PC\"><!-- PC端首页 -->\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<div class=\"mbox pb48 clear\">\r\n");
      out.write("\t\t\t<div class=\"mright\">\r\n");
      out.write("\t\t\t\t<div class=\"qrbox\">\r\n");
      out.write("\t\t\t\t\t<div class=\"qr\"><img src=\"../../../images/qr.png\" width=\"180\" height=\"180\" alt=\"\" id=\"qrcode\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"dl clear\">\r\n");
      out.write("\t\t\t\t\t<div class=\"dl-list\">\r\n");
      out.write("\t\t\t\t\t\t<div><a href=\"javascript:void(0)\" class=\"dl-iphone\" id=\"ios_download\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t<p>版本 1.0.4（14.9MB）</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"dl-list\">\r\n");
      out.write("\t\t\t\t\t\t<div><a href=\"javascript:void(0)\" class=\"dl-android\" id=\"android_download\"></a></div>\r\n");
      out.write("\t\t\t\t\t\t<p>版本 4.1.0（4.8MB）</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"infobox\">\r\n");
      out.write("\t\t<div class=\"main\">\r\n");
      out.write("\t\t\t<ul class=\"infolist clear\">\r\n");
      out.write("\t\t\t\t<li><img src=\"../../../images/info1.png\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"../../../images/info2.png\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t<li><img src=\"../../../images/info3.png\" alt=\"\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"foot s1\">\r\n");
      out.write("\t\t\t\t<p><em>@</em><span>库客音乐</span><span>京ICP证030879号</span><span>Copyright kuke.com All rights reserved</span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<img src=\"../../../images/a1.png\" alt=\"\" class=\"a1\">\r\n");
      out.write("\t<img src=\"../../../images/a2.png\" alt=\"\" class=\"a2\">\r\n");
      out.write("\t<img src=\"../../../images/a3.png\" alt=\"\" class=\"a3\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrap pt54 dpn\" id=\"Mobile\"><!-- 移动端首页 -->\r\n");
      out.write("\t<div class=\"bg\" id=\"bg\"></div>\r\n");
      out.write("\t<div class=\"dlbox\">\r\n");
      out.write("\t\t<h1>对眼猫 让音乐找到你</h1>\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" id=\"mdownload\">马上下载</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"swipe\">\r\n");
      out.write("\t\t<ul class=\"clear\" id=\"swipe\">\r\n");
      out.write("\t\t\t<li><img src=\"../../../images/swipe01.png\" alt=\"\" width=\"239\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"../../../images/swipe02.png\" alt=\"\" width=\"239\"></li>\r\n");
      out.write("\t\t\t<li><img src=\"../../../images/swipe03.png\" alt=\"\" width=\"239\"></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<p class=\"foot\"><em>@</em><span>库客音乐</span><span>京ICP证030879号</span><span>Copyright kuke.com</span><span>All rights reserved</span></p>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"pop-bg\"></div>\r\n");
      out.write("<div id=\"popup\"><img width=\"100%\" alt=\"\" src=\"http://ponent.kuke.com/static/images/notice.png\"></div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function G(id){\r\n");
      out.write("\treturn document.getElementById(id);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("G(\"ios_download\").onclick=function(){\r\n");
      out.write("\tlocation.href=\"https://itunes.apple.com/app/id1001444595\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("G(\"android_download\").onclick=function(){\r\n");
      out.write("\tlocation.href=\"http://static.kuke.com/android/kkmusicfm3nd.apk\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var ua = navigator.platform;\r\n");
      out.write("var pc = /win32|macintel|macintosh|android/i.test(navigator.platform);\r\n");
      out.write("// var mobile = /ipod|iphone|ipad|android|iemobile|nokiabrowser|symbian|blackberry|playbook|bb10/i.test(navigator.userAgent);\r\n");
      out.write("\r\n");
      out.write("if(!pc){\r\n");
      out.write("\tG(\"device\").href = \"../../../css/dym-m.css\";\r\n");
      out.write("\tG(\"PC\").style.display = \"none\";\r\n");
      out.write("\tG(\"Mobile\").style.display = \"block\";\r\n");
      out.write("\tswipeNum();\r\n");
      out.write("}else{\r\n");
      out.write("\tG(\"device\").href = \"../../../css/dym.css\";\r\n");
      out.write("\tG(\"PC\").style.display = \"block\";\r\n");
      out.write("\tG(\"Mobile\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("var ua1 = navigator.userAgent;\r\n");
      out.write("//alert(ua1);\r\n");
      out.write("var isWeixin = /micromessenger/i.test(ua1);\r\n");
      out.write("var isAndroid = /android/i.test(ua1);\r\n");
      out.write("var isIphone = /ipod|iphone|ipad/i.test(ua1);\r\n");
      out.write("if(isWeixin){\r\n");
      out.write("\tG('mdownload').onclick = function(){\r\n");
      out.write("\t\tshowpop();\r\n");
      out.write("\t}\r\n");
      out.write("//\tG('#popup').ontouchstart = function(){\r\n");
      out.write("//\t\thidepop();\r\n");
      out.write("//\t}\r\n");
      out.write("\t\r\n");
      out.write("}else{\r\n");
      out.write("\tif(isAndroid){\r\n");
      out.write("\t\tG('mdownload').onclick = function(){\r\n");
      out.write("\t\t\tlocation.href=\"http://static.kuke.com/android/kkmusicfm3nd.apk\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else if(isIphone){\r\n");
      out.write("\t\tG('mdownload').onclick = function(){\r\n");
      out.write("\t\t\tlocation.href=\"https://itunes.apple.com/app/id1001444595\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function swipeNum(){ //左右滑动\r\n");
      out.write("\tG(\"swipe\").ontouchstart = function(event){\r\n");
      out.write("\t\tvar\ttouch =\tevent.targetTouches[0]; //touches数组对象获得屏幕上所有的touch，取第一个touch\r\n");
      out.write("\t\tstartPos = {x:touch.pageX,y:touch.pageY,time:+new Date}; //取第一个touch的坐标值\r\n");
      out.write("\t\tisScrolling\t= 0; //这个参数判断是垂直滚动还是水平滚动\r\n");
      out.write("\t}\r\n");
      out.write("\tG(\"swipe\").ontouchmove = function(event){\r\n");
      out.write("\t\tif(event.targetTouches.length <\t1 || event.scale &&\tevent.scale\t!==\t1){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar\ttouch =\tevent.targetTouches[0];\r\n");
      out.write("\t\tendPos = {x:touch.pageX\t- startPos.x,y:touch.pageY - startPos.y};\r\n");
      out.write("\t\tisScrolling\t= Math.abs(endPos.x) < Math.abs(endPos.y) ?\t1 : 0; //isScrolling为1时，表示纵向滑动，0为横向滑动\r\n");
      out.write("\t\tif(isScrolling === 0){\r\n");
      out.write("\t\t\tevent.preventDefault(); //阻止触摸事件的默认行为，即阻止滚屏\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tvar index = 0;\r\n");
      out.write("\tvar swipelist = document.getElementById(\"swipe\").getElementsByTagName(\"li\");\r\n");
      out.write("\tvar len = swipelist.length;\r\n");
      out.write("\tG(\"swipe\").ontouchend = function(event){\r\n");
      out.write("\t\tvar\tduration = +new\tDate - startPos.time; //滑动的持续时间\r\n");
      out.write("\t\tif(Number(duration)\t> 10){\r\n");
      out.write("\t\t\t//判断是左移还是右移，当偏移量大于10时执行\r\n");
      out.write("\t\t\tif(endPos.x\t> 10){ //向右滑动\r\n");
      out.write("\t\t\t\tvar moveNum = 0;\r\n");
      out.write("\t\t\t\tvar moveSpeed = 1;\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.transform = \"translate(\" + moveNum + \"px,0)\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.webkitTransform = \"translate(\" + moveNum + \"px,0)\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.mozTransform = \"translate(\" + moveNum + \"px,0)\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.transitionDuration = moveSpeed + \"s\";\r\n");
      out.write("\t\t\t}else if(endPos.x <\t-10){ //向左滑动\r\n");
      out.write("\t\t\t\tvar moveNum = -406;\r\n");
      out.write("\t\t\t\tvar moveSpeed = 1;\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.transform = \"translate(\" + moveNum + \"px,0)\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.webkitTransform = \"translate(\" + moveNum + \"px,0)\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.mozTransform = \"translate(\" + moveNum + \"px,0)\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.transitionDuration = moveSpeed + \"s\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.webkitTransitionDuration = moveSpeed + \"s\";\r\n");
      out.write("\t\t\t\tG(\"swipe\").style.mozTransitionDuration = moveSpeed + \"s\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var ua1 = navigator.userAgent;\r\n");
      out.write("//alert(ua1);\r\n");
      out.write("var isWeixin = /micromessenger/i.test(ua1);\r\n");
      out.write("var isAndroid = /android/i.test(ua1);\r\n");
      out.write("var isIphone = /ipod|iphone|ipad/i.test(ua1);\r\n");
      out.write("if(isWeixin){\r\n");
      out.write("\tG('mdownload').onclick = function(){\r\n");
      out.write("\t\tshowpop();\r\n");
      out.write("\t}\r\n");
      out.write("//\tG('#popup').ontouchstart = function(){\r\n");
      out.write("//\t\thidepop();\r\n");
      out.write("//\t}\r\n");
      out.write("\t\r\n");
      out.write("}else{\r\n");
      out.write("\tif(isAndroid){\r\n");
      out.write("\t\tG('mdownload').onclick = function(){\r\n");
      out.write("\t\t\tlocation.href=\"http://static.kuke.com/android/kkmusicfm3nd.apk\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else if(isIphone){\r\n");
      out.write("\t\tG('mdownload').onclick = function(){\r\n");
      out.write("\t\t\tlocation.href=\"https://itunes.apple.com/app/id1001444595\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showpop(){\r\n");
      out.write("\tdocument.getElementById('pop-bg').style.display = 'block';\r\n");
      out.write("\tdocument.getElementById('popup').style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("function hidepop(){\r\n");
      out.write("//\talert(1)\r\n");
      out.write("\tdocument.getElementById('pop-bg').style.display = 'none';\r\n");
      out.write("\tdocument.getElementById('popup').style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
